[package]
name = "blades"
version = "0.1.0"
authors = ["Maroš Grego <maros@grego.site>"]
edition = "2018"

[dependencies]
toml = "0.5.6"
ramhorns = "0.10"
beef = { version = "0.4.4", features = ["impl_serde"]}
serde = { version = "1.0.114", features = ["derive"] }
custom_error = "1.8.0"
chrono = {version = "0.4.12", features = ["serde"] }
ahash = "0.4"
parking_lot = "0.11"
rayon = "1.3.1"
structopt = "0.3.18"

[profile.release]
lto = true

[profile.bench]
lto = true
